In [1]:
import numpy as np
a=np.array([1,2,38,7,9,8,10])
print(a)

[ 1  2 38  7  9  8 10]


In [2]:
print('max number in the list is',max(a))

max number in the list is 38


In [3]:
print('min number in the list is',min(a))

min number in the list is 1


In [5]:
print('length of array is',len(a))

length of array is 7


In [6]:
print('sum of array is',sum(a))

sum of array is 75


In [7]:
print('numbers after 2',a[2:])
print('last 2 after 2',a[-2:])

numbers after 2 [38  7  9  8 10]
last 2 after 2 [ 8 10]


In [2]:
import numpy as np
a=np.array([[1,2,38],[7,9,8],[4,7,9]])
b=np.zeros([4,4])
print(a)
print('zero matrix \n',b)

[[ 1  2 38]
 [ 7  9  8]
 [ 4  7  9]]
zero matrix 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [4]:
b=np.full([4,4],2)
print('2 matrix \n',b)

2 matrix 
 [[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]


In [13]:
b=np.full([3,3],2)
print('2 matrix \n',b)

2 matrix 
 [[2 2 2]
 [2 2 2]
 [2 2 2]]


In [12]:
b=np.full([3,3],9)
print('9 matrix \n',b)

9 matrix 
 [[9 9 9]
 [9 9 9]
 [9 9 9]]


identity matrix 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [17]:
c=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [18]:
print(a+c)

[[ 2  4 41]
 [11 14 14]
 [11 15 18]]


In [19]:
print(np.add(a,c))

[[ 2  4 41]
 [11 14 14]
 [11 15 18]]


In [20]:
print(a-c)

[[ 0  0 35]
 [ 3  4  2]
 [-3 -1  0]]


In [21]:
print(np.subtract(a,c))

[[ 0  0 35]
 [ 3  4  2]
 [-3 -1  0]]


In [22]:
print(np.log(c))

[[0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]
 [1.94591015 2.07944154 2.19722458]]


In [23]:
print(np.log2(c))

[[0.         1.         1.5849625 ]
 [2.         2.32192809 2.5849625 ]
 [2.80735492 3.         3.169925  ]]


In [24]:
print(np.log10(c))

[[0.         0.30103    0.47712125]
 [0.60205999 0.69897    0.77815125]
 [0.84509804 0.90308999 0.95424251]]


In [26]:
e=np.random.randn(3,3)
print(e)

[[-0.37015361  0.02286686  0.72977214]
 [-1.08352616  0.88885345 -0.08060171]
 [ 0.0187436  -0.87376155 -0.84023897]]


In [28]:
f=np.random.randint(1,10,[4,3,3])
print(f)

[[[7 8 1]
  [3 1 3]
  [6 7 5]]

 [[7 2 2]
  [9 6 4]
  [9 6 5]]

 [[3 4 9]
  [1 6 1]
  [3 5 2]]

 [[4 9 1]
  [5 3 5]
  [7 4 9]]]


In [30]:
g=np.random.randint(1,9,size=(3,3))
print(g)

[[7 2 2]
 [4 4 4]
 [3 2 1]]


In [30]:
h=np.arange(1,14,1)
print(h)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13]


In [34]:
m=np.linspace(1,100,num=10)
print(m)

[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]


In [39]:
i=np.random.randint(9,size=(4,4))
print(i)

[[1 2 1 1]
 [0 8 0 8]
 [1 7 4 6]
 [2 3 1 4]]


In [40]:
j=np.random.randint(9,size=(3,3))
print(j)

[[2 3 7]
 [5 0 4]
 [6 8 4]]


In [35]:
#sd, mean,median,max,min,avg,variance
import numpy as np
k=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(k)
print('std dev',np.std(k))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
std dev 2.581988897471611


In [42]:
print('average',np.average(k))

average 5.0


In [43]:
print('min',np.min(k))

min 1


In [45]:
print('maximum',np.max(k))

maximum 9


In [46]:
print('mean',np.mean(k))

mean 5.0


In [47]:
print('median',np.median(k))

median 5.0


In [49]:
print('variance',np.var(k))

variance 6.666666666666667


In [51]:
#sin,cos and tan of array
print('sine of array',np.sin(k))

sine of array [[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]
 [ 0.6569866   0.98935825  0.41211849]]


In [52]:
print('cos of array',np.cos(k))

cos of array [[ 0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029]
 [ 0.75390225 -0.14550003 -0.91113026]]


In [53]:
print('tan of array',np.tan(k))

tan of array [[ 1.55740772 -2.18503986 -0.14254654]
 [ 1.15782128 -3.38051501 -0.29100619]
 [ 0.87144798 -6.79971146 -0.45231566]]


In [54]:
print('size of array',k.size)

size of array 9


In [55]:
print('shape of array',k.shape)

shape of array (3, 3)


In [57]:
print('sum of array',sum(k))

sum of array [12 15 18]


In [58]:
print('numbers after 2',k[2:])

numbers after 2 [[7 8 9]]


In [59]:
print('last 2 numbers',k[-2:])

last 2 numbers [[4 5 6]
 [7 8 9]]


In [1]:
# 1dim array
import array as arr
a=arr.array('i',[1,2,38,7,9])
print(a)
#insert a numer in array
a.insert(2,3)
print(a)
#append
a.append(6)
print(a)
#remove a number from array
a.remove(38)
print(a)
#count a particular numer from array
print('counting 1',a.count(1))
#max number from array
print('max number in the array is',max(a))
#min number from array
print('min number in the array is',min(a))
#length of array
print('length of arraay is',len(a))
#sum of all the numbers from array
print('sum of arraay is',sum(a))
#slicing in froma given position array
print('numbers after 2',a[2:])
print('numbers after 2',a[-2:])


array('i', [1, 2, 38, 7, 9])
array('i', [1, 2, 3, 38, 7, 9])
array('i', [1, 2, 3, 38, 7, 9, 6])
array('i', [1, 2, 3, 7, 9, 6])
counting 1 1
max number in the array is 9
min number in the array is 1
length of arraay is 6
sum of arraay is 28
numbers after 2 array('i', [3, 7, 9, 6])
numbers after 2 array('i', [9, 6])


In [2]:
# 2 dim array
import numpy as np
a=np.array([1,2,38,7,9,8,10])
print(a)
print('max number in the list is',max(a))
print('min number in the list is',min(a))
print('length of arraay is',len(a))
print('sum of arraay is',sum(a))
print(a)
print('numbers after 2',a[2:])
print('last 2 numbers ',a[-2:])


[ 1  2 38  7  9  8 10]
max number in the list is 38
min number in the list is 1
length of arraay is 7
sum of arraay is 75
[ 1  2 38  7  9  8 10]
numbers after 2 [38  7  9  8 10]
last 2 numbers  [ 8 10]


In [3]:
# 2 dim array
import numpy as np
a=np.array([[1,2,38],[7,9,8],[4,7,9]])
b=np.zeros([3,3])
print(' zero matrix \n',b)
b=np.full([3,3],1)
print(' 1 matrix \n',b)
b=np.full([3,3],2)
print(' 2 matrix \n',b)
b=np.full([3,3],9)
print(' 9 matrix \n',b)
b=np.eye(3)
print(' identity matrix \n',b)

 zero matrix 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
 1 matrix 
 [[1 1 1]
 [1 1 1]
 [1 1 1]]
 2 matrix 
 [[2 2 2]
 [2 2 2]
 [2 2 2]]
 9 matrix 
 [[9 9 9]
 [9 9 9]
 [9 9 9]]
 identity matrix 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [4]:
# 2 dim array
import numpy as np
a=np.array([[1,2,38],[7,9,8],[4,7,9]])
print(a)
c=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(c)
print(a+c)
print(np.add(a,c))
print(a-c)
print(np.subtract(a,c))

[[ 1  2 38]
 [ 7  9  8]
 [ 4  7  9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 2  4 41]
 [11 14 14]
 [11 15 18]]
[[ 2  4 41]
 [11 14 14]
 [11 15 18]]
[[ 0  0 35]
 [ 3  4  2]
 [-3 -1  0]]
[[ 0  0 35]
 [ 3  4  2]
 [-3 -1  0]]


In [5]:
# 2 dim array
import numpy as np
a=np.array([[1,2,38],[7,9,8],[4,7,9]])
print(a)
print('size of array is',a.size)
print('shape of array',a.shape)
print('sum of arraay is',sum(a))
print('numbers after 2',a[2:])
print('last 2 numbers ',a[-2:])
b=np.zeros([3,3])
print(' zero matrix \n',b)
b=np.ones([3,3])
print(b)
b=np.full([3,3],9)
print(b)
b=np.eye(3)
print(b)
c=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a+c)
print(np.add(a,c))
print(a-c)
print(np.subtract(a,c))
print(c)
print(np.sin(c))
print(np.cos(c))
print(np.tan(c))
print(np.log(c))
print(np.log2(c))
print(np.log10(c))
print(np.std(c))
print(np.average(c))
print(np.min(c))
print(np.max(c))
print(np.mean(c))
print(np.median(c))
print(np.var(c))
d=np.array([1,0,-1])
print(np.arcsin(d))
e=np.random.randn(2,2)
print(e)
f=np.random.randint(1,[3,3,3])
print(f)
g=np.random.randint(9,size=(3,3))
print(g)
h=np.arange(1,14,4)
print(h)
m=np.linspace(0,5,num=20)
print(m)
print(np.linalg.det(a))



[[ 1  2 38]
 [ 7  9  8]
 [ 4  7  9]]
size of array is 9
shape of array (3, 3)
sum of arraay is [12 18 55]
numbers after 2 [[4 7 9]]
last 2 numbers  [[7 9 8]
 [4 7 9]]
 zero matrix 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[9 9 9]
 [9 9 9]
 [9 9 9]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[ 2  4 41]
 [11 14 14]
 [11 15 18]]
[[ 2  4 41]
 [11 14 14]
 [11 15 18]]
[[ 0  0 35]
 [ 3  4  2]
 [-3 -1  0]]
[[ 0  0 35]
 [ 3  4  2]
 [-3 -1  0]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]
 [ 0.6569866   0.98935825  0.41211849]]
[[ 0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029]
 [ 0.75390225 -0.14550003 -0.91113026]]
[[ 1.55740772 -2.18503986 -0.14254654]
 [ 1.15782128 -3.38051501 -0.29100619]
 [ 0.87144798 -6.79971146 -0.45231566]]
[[0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]
 [1.94591015 2.07944154 2.19722458]]
[[0.         1.         1.5849625 ]
 [2.

In [8]:
# 2 dim array
import numpy as np
a=np.array([[1,2,38],[7,9,8],[4,7,9]])
print(a)
print('size of array is',a.size)
print('shape of array',a.shape)
print('sum of arraay is',sum(a))
print('numbers after 2',a[2:])
print('last 2 numbers ',a[-2:])


[[ 1  2 38]
 [ 7  9  8]
 [ 4  7  9]]
size of array is 9
shape of array (3, 3)
sum of arraay is [12 18 55]
numbers after 2 [[4 7 9]]
last 2 numbers  [[7 9 8]
 [4 7 9]]
